config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  post '/enroll', to: 'courses#enroll'

  get '/search', to: 'courses#search'
  get '/signup', to: 'users#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/instructors', to: 'instructors#index'

  get '/subjects',   to: 'subjects#index'

  get '/courses',    to: 'courses#index'

  resources :users do
	collection do
		get 'search'
	end
  end

  resources :enrollments
  resources :instructors, only: [:index]
  resources :subjects, only: [:index]
  resources :courses, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :enrollments, dependent: :destroy
  has_many :users, :through => :enrollments
  has_many :course_subject, dependent:   :destroy
  has_many :subjects, :through => :course_subject
  
  #def self.search(search)
	#	where(["name LIKE ? ","%#{params\[\title\]}%")
  #end
  
end

app/models/course_subject.rb
class CourseSubject < ApplicationRecord
  belongs_to :course, optional: true
  belongs_to :subject, optional: true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :course, optional: true
  validates :user_id, presence: true
  validates :course_id, presence: true
end

app/models/instructor.rb
class Instructor < ApplicationRecord
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :course_subject, dependent:   :destroy
  has_many :courses, :through => :course_subject
  self.primary_key = "indicator"
end

app/models/user.rb
class User < ApplicationRecord

  has_many :enrollments, dependent: :destroy
  has_many :courses, :through => :enrollments
  
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  def hello
    render html: "hello, world!"
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def search
	@subjectsList = Subject.all.map{ |sub| [sub.name, sub.id] }
	@courseQuery = params[:query]
	@subjectQuery = params[:subject]
	#@courses = Subject.where("subjects.indicator LIKE ?", "%#{@subjectQuery}%")
	@courses = Course.where("courses.name LIKE ?", "%#{@courseQuery}%")
	#@courses = Course.joins(:course_subjects)#.where("courses.name LIKE ?", "%#{@courseQuery}%").where("subjects.indicator LIKE ?", "%#{@subjectQuery}%")
  end

  def index
    @courses = Course.all.order('name ASC')
  end

  def enroll
    if Enrollment.where(:user_id => current_user.id, :course_id => params[:id]).blank?
      @enrollment = Enrollment.new(user_id: current_user.id, course_id: params[:id])
      @enrollment.save
      flash[:success] = "You have successfully enrolled in #{params[:name]}"
      redirect_to "/"
    else
      flash[:warning] = "You are already enrolled in that class!"
    end
  end

  def unenroll

  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  def new
    @enrollment = Enrollment.new
  end


end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  def index
	@instructors = Instructor.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      # Create an error message.
	  flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @enrollments = Enrollment.where("enrollments.user_id LIKE ?", "%#{current_user.id}%")
    end
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
	@subjects = Subject.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
	  log_in @user
	  flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
	  <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
	  	<td><%= course.code %></td>
        <td><%= course.name %></td>
		<td><%= course.desc %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/courses/search.html.erb

<div class="row">
  <div class="col-md-8 col-md-offset-2">
	  <h1>Search Classes</h1>
		<%= form_tag(search_path, method: "get") do %>
		  <div class="col-md-8 col-md-offset-2">
			<%= label_tag(:query, "Class Name:") %>
			<%= text_field_tag(:query, "") %>
			<%= select_tag(:subject, options_for_select(@subjectsList), {:include_blank => true})%>
			<%= submit_tag("Search") %>
		  </div>
		<% end %>
	</div>
</div>


<% if @courses.blank? %>
<p>There are no courses containing your search</p>

<% else %>
<div class="row">
<p id="notice"><%= notice %></p>
<h1>Courses</h1>


<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
	  	    <td><%= course.code %></td>
          <td><%= course.name %></td>
          <% if logged_in? %>
          <td><%= button_to "Enroll", { action: "enroll", id: course.id, name: course.name, data: { confirm: "Are you sure?" }}  %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>
<% end %>

app/views/instructors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Instructors</h1>

<table>
  <thead>
    <tr>
      <th>Last Name</th>
      <th>Email</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instructors.each do |instructor| %>
      <tr>
        <td><%= instructor.last %></td>
        <td><%= instructor.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>Welcome to the Course Catalog</h1>

  <% if logged_in? %>
  <h2>Welcome <%= current_user.name %></h2>
  <% if @enrollments.blank? %>
    <p>You are currently not enrolled in any classes now</p>
    <%= link_to "Enroll Now!", search_path, class: "btn btn-lg btn-primary" %>
  <% else %>
  <div class="row">
  <p id="notice"><%= notice %></p>
  <h5>You are enrolled in the following courses:</h5>
  <table>
    <thead>
      <tr>
        <th>Code</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @enrollments.each do |enrollment| %>
        <tr>
  	  	    <td><%= enrollment.course_id %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  </div>
  <%= link_to "Enroll in more classes!", search_path, class: "btn btn-md btn-primary" %>
  <% end %>

  <% else %>
  <%= link_to "Login", login_path, class: "btn btn-lg btn-primary" %>
  <%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary" %>
  <% end %>
</div>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subjects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
	  <th>ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.name %></td>
		<td><%= subject.indicator %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>