config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  post '/enroll', to: 'courses#enroll'

  get '/search', to: 'courses#search'
  get '/signup', to: 'users#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/instructors', to: 'instructors#index'

  get '/subjects',   to: 'subjects#index'

  get '/courses',    to: 'courses#index'

  resources :users do
	collection do
		get 'search'
	end
  end

  resources :enrollments
  resources :instructors, only: [:index]
  resources :subjects, only: [:index]
  resources :courses, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :enrollments, dependent: :destroy
  has_many :users, :through => :enrollments
  has_many :course_subject, dependent:   :destroy
  has_many :subjects, :through => :course_subject
  
  #def self.search(search)
	#	where(["name LIKE ? ","%#{params\[\title\]}%")
  #end
  
end

app/models/course_subject.rb
class CourseSubject < ApplicationRecord
  belongs_to :course, optional: true
  belongs_to :subject, optional: true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :course, optional: true
  validates :user_id, presence: true
  validates :course_id, presence: true
end

app/models/instructor.rb
class Instructor < ApplicationRecord
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :course_subject, dependent:   :destroy
  has_many :courses, :through => :course_subject
  self.primary_key = "indicator"
end

app/models/user.rb
class User < ApplicationRecord

  has_many :enrollments, dependent: :destroy
  has_many :courses, :through => :enrollments
  
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  def hello
    render html: "hello, world!"
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def search
	@subjectsList = Subject.all.map{ |sub| [sub.name, sub.id] }
	@courseQuery = params[:query]
	@subjectQuery = params[:subject]
	#@courses = Subject.where("subjects.indicator LIKE ?", "%#{@subjectQuery}%")
	@courses = Course.where("courses.name LIKE ?", "%#{@courseQuery}%")
	#@courses = Course.joins(:course_subjects)#.where("courses.name LIKE ?", "%#{@courseQuery}%").where("subjects.indicator LIKE ?", "%#{@subjectQuery}%")
  end

  def index
    @courses = Course.all.order('name ASC')
  end

  def enroll
    if Enrollment.where(:user_id => current_user.id, :course_id => params[:id]).blank?
      @enrollment = Enrollment.new(user_id: current_user.id, course_id: params[:id])
      @enrollment.save
      flash[:success] = "You have successfully enrolled in #{params[:name]}"
      redirect_to "/"
    else
      flash[:warning] = "You are already enrolled in that class!"
    end
  end

  def unenroll

  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  def new
    @enrollment = Enrollment.new
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      # Create an error message.
	  flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
	@subjects = Subject.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
	  log_in @user
	  flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Course Catalog", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Subjects", subjects_path %></li>
		  <li><%= link_to "Courses", courses_path %></li>
		  <li><%= link_to "Instructors", instructors_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
	<div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>